set CXX and CXXFLAGS for building bundled pb library
git-svn-id: file:///home/git/hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/flowWorkspace@110368 bc3139a8-67e5-0310-9ffc-ced21a209358

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3572,7 +3572,14 @@ fi
 
 
 # Check the compiler configured with R
-COMPILER=`${R_HOME}/bin/R CMD config CC`
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+  echo "could not determine R_HOME"
+  exit 1
+fi
+COMPILER=`"${R_HOME}/bin/R" CMD config CC`
+MYCXX=`"${R_HOME}/bin/R" CMD config CXX`
+MYCXXFLAGS=`"${R_HOME}/bin/R" CMD config CXXFLAGS`
 MAKE=`${R_HOME}/bin/R CMD config MAKE`
 
 #xml2 lib
@@ -3678,6 +3685,8 @@ $as_echo "$as_me: No directory was specified for --with-protobuf. Using bundled 
 		fi;
 		cd ${PBBUILD};
 		../${BASEPBNAME}/configure --enable-static=no
+		CXX=${MYCXX}
+		CXXFLAGS=${MYCXXFLAGS}
 		$MAKE
 
 		PB_CFLAGS="-I${BASEPBNAME}/src"
@@ -3695,9 +3704,9 @@ fi
 
 
 PKG_CPPFLAGS="$XML2_CFLAGS $PB_CFLAGS"
-if test "${COMPILER}" = "clang"; then
+#if test "${COMPILER}" = "clang"; then
   PKG_CPPFLAGS+=" -ftemplate-depth=900"
-fi
+#fi
 
 PKG_LIBS="$XML2_LIBS $PB_LIBS"
 
